name: SonarCloud Scan

on:
  workflow_call:
    inputs:
      project-name:
        required: false
        type: string

jobs:
  sonarcloud-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "zulu"

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
        with:
          args: >
              -Dsonar.organization=nkpfluke
              -Dsonar.projectKey=DemoSonarCloud
