name: SonarCloud Scan

on:
  workflow_call:
    inputs:
      project-name:
        required: false
        type: string

jobs:
  sonarcloud-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "zulu"

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build Java Project
        run: mvn clean package

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: 31218bfed29d9d79f77982becdb8b46f705651ba
        with:
          args: >
              -D sonar.organization=niteshorgkey
              -D sonar.projectKey=nkpfluke_DemoSonarCloud
              -D sonar.sources=src/main/java
              -D sonar.java.binaries=target/classes
